// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jknweassrqdvoscjttbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbndlYXNzcnFkdm9zY2p0dGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTQ1MTksImV4cCI6MjA2OTg3MDUxOX0.QznyGGk5ghDX6zPWoiiGc3hhVx6mTPY8_4Zq2u3ABJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});